// ============================================================
//  IGNITE — Products Data Module
//  All product data lives here. Add/remove products easily.
// ============================================================

const products = [
  {
    id: 1,
    name: "Executive Laptop Bag",
    category: "accessories",
    price: 189.99,
    originalPrice: 249.99,
    rating: 4.8,
    reviews: 214,
    badge: "Best Seller",
    badgeType: "success",
    image: "public/images/product-bag.png",
    description:
      'Premium full-grain leather laptop bag designed for the modern executive. Fits laptops up to 16" with dedicated compartments for all your business essentials.',
    features: [
      "Full-grain leather",
      'Fits up to 16" laptop',
      "Gold-plated hardware",
      "RFID-blocking pocket",
    ],
    stock: 12,
    tags: ["leather", "laptop", "travel", "premium"],
  },
  {
    id: 2,
    name: "ProNoise ANC Headphones",
    category: "electronics",
    price: 329.99,
    originalPrice: 399.99,
    rating: 4.9,
    reviews: 512,
    badge: "Top Rated",
    badgeType: "warning",
    image: "public/images/product-headphones.png",
    description:
      "Industry-leading active noise cancellation. Crystal-clear audio for boardroom calls, deep focus sessions, and everything in between.",
    features: [
      "40hr battery life",
      "Active Noise Cancellation",
      "Multipoint Bluetooth 5.3",
      "Foldable premium design",
    ],
    stock: 28,
    tags: ["audio", "wireless", "noise-cancelling", "productivity"],
  },
  {
    id: 3,
    name: "Apex Exec Smartwatch",
    category: "electronics",
    price: 449.99,
    originalPrice: 549.99,
    rating: 4.7,
    reviews: 387,
    badge: "New",
    badgeType: "info",
    image: "public/images/product-watch.png",
    description:
      "Where luxury meets intelligence. The Apex Exec tracks your health metrics while keeping you connected to what matters most — your business.",
    features: [
      "Always-on AMOLED",
      "ECG & SpO2 monitor",
      "NFC payments",
      "7-day battery",
    ],
    stock: 9,
    tags: ["watch", "smart", "luxury", "health"],
  },
  {
    id: 4,
    name: "ErgoFlow Pro Chair",
    category: "office",
    price: 799.99,
    originalPrice: 999.99,
    rating: 4.9,
    reviews: 193,
    badge: "Premium",
    badgeType: "danger",
    image:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    description:
      "Engineered for peak performance. The ErgoFlow Pro provides lumbar support, adjustable armrests, and breathable mesh to keep you sharp through the longest days.",
    features: [
      "Lumbar support system",
      "Breathable mesh back",
      "4D adjustable armrests",
      "12-year warranty",
    ],
    stock: 5,
    tags: ["furniture", "ergonomic", "office", "comfort"],
  },
  {
    id: 5,
    name: "Obsidian Fountain Pen Set",
    category: "stationery",
    price: 124.99,
    originalPrice: null,
    rating: 4.6,
    reviews: 98,
    badge: "Limited",
    badgeType: "secondary",
    image:
      "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80",
    description:
      "Make every signature count. The Obsidian pen set exudes executive presence — matte black barrel with 24K gold nib, delivered in a premium gift box.",
    features: [
      "24K gold nib",
      "Matte black finish",
      "Comes with 5 ink cartridges",
      "Luxury gift box",
    ],
    stock: 20,
    tags: ["pen", "stationery", "luxury", "writing"],
  },
  {
    id: 6,
    name: "UltraSlim Standing Desk",
    category: "office",
    price: 1199.99,
    originalPrice: 1499.99,
    rating: 4.8,
    reviews: 145,
    badge: "Sale",
    badgeType: "danger",
    image:
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",
    description:
      "Electric height-adjustable desk with memory presets, a sleek cable management system, and a premium bamboo surface. Work your way.",
    features: [
      "Electric height adjustment",
      "4 memory presets",
      "Anti-collision tech",
      "Built-in USB-C charging",
    ],
    stock: 7,
    tags: ["desk", "standing", "office", "productivity"],
  },
  {
    id: 7,
    name: "TravelShield Pro Briefcase",
    category: "accessories",
    price: 259.99,
    originalPrice: 319.99,
    rating: 4.5,
    reviews: 71,
    badge: null,
    badgeType: null,
    image:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    description:
      "A hard-shell briefcase engineered for busy executives. TSA-approved, waterproof, and equipped with a smart digital lock accessible via Bluetooth.",
    features: [
      "Polycarbonate shell",
      "Smart Bluetooth lock",
      "Waterproof IP67",
      "Integrated USB charger",
    ],
    stock: 14,
    tags: ["travel", "briefcase", "smart", "security"],
  },
  {
    id: 8,
    name: "Lumina 4K Monitor",
    category: "electronics",
    price: 689.99,
    originalPrice: 799.99,
    rating: 4.7,
    reviews: 302,
    badge: "Hot",
    badgeType: "danger",
    image:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80",
    description:
      'A 27" 4K IPS display with factory calibration, 99% sRGB coverage, and USB-C docking — perfect for creatives and data-driven executives.',
    features: [
      '27" 4K IPS panel',
      "99% sRGB calibrated",
      "USB-C 90W docking",
      "Ultra-slim bezel design",
    ],
    stock: 18,
    tags: ["monitor", "4K", "display", "productivity"],
  },
  {
    id: 9,
    name: "BusinessCard Pro Wallet",
    category: "accessories",
    price: 79.99,
    originalPrice: null,
    rating: 4.4,
    reviews: 56,
    badge: null,
    badgeType: null,
    image:
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    description:
      "A slim, minimalist cardholder wallet crafted from full-grain leather. Holds up to 12 cards with RFID shielding and a quick-access slot.",
    features: [
      "Full-grain leather",
      "Holds 12 cards",
      "RFID blocking",
      "Slim profile 6mm",
    ],
    stock: 40,
    tags: ["wallet", "leather", "slim", "RFID"],
  },
  {
    id: 10,
    name: "Ignite Business Planner",
    category: "stationery",
    price: 49.99,
    originalPrice: null,
    rating: 4.8,
    reviews: 420,
    badge: "Fan Favourite",
    badgeType: "success",
    image:
      "https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&q=80",
    description:
      "The planner built for high-performers. Goal tracking, weekly reviews, meeting logs, and a premium linen cover that feels as serious as you are.",
    features: [
      "Dated 12-month layout",
      "Goal & habit tracking",
      "Linen hardcover",
      "Lay-flat binding",
    ],
    stock: 55,
    tags: ["planner", "productivity", "stationery", "goals"],
  },
  {
    id: 11,
    name: "NanoMesh Laptop Stand",
    category: "office",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.6,
    reviews: 178,
    badge: null,
    badgeType: null,
    image:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
    description:
      "Aluminium mesh laptop stand with 6 adjustable angles and a built-in cooling channel. Elevate your setup, elevate your productivity.",
    features: [
      "6 adjustable angles",
      "Aluminium alloy",
      "Foldable & portable",
      "Fits all laptops",
    ],
    stock: 33,
    tags: ["laptop", "stand", "accessories", "desk"],
  },
  {
    id: 12,
    name: "SignalX Wireless Charger",
    category: "electronics",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.3,
    reviews: 89,
    badge: "Sale",
    badgeType: "danger",
    image:
      "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&q=80",
    description:
      "15W fast wireless charging pad with multi-device support. Charge your phone, earbuds, and watch simultaneously — perfectly minimal on your desk.",
    features: [
      "15W fast charge",
      "3-device simultaneous",
      "LED status indicator",
      "Qi universal compatible",
    ],
    stock: 22,
    tags: ["charging", "wireless", "electronics", "desk"],
  },
];

export default products;
